# $Id: makefile.unx,v 1.3 2019-08-08 09:45:41+03 dstef Exp root $

target=ftest3
warnings=-Wall

#CC=clang
RM=rm

$(target): $(target).c
	$(CC) $(warnings) -D_GNU_SOURCE=1 -D_BSD_SOURCE=1 -o $(target) $(target).c -pthread

static: $(target).c
	$(CC) -static $(warnings) -D_GNU_SOURCE=1 -D_BSD_SOURCE=1 -o $(target) $(target).c -pthread
	
clean:
	$(RM) -f $(target)
